services:
  - type: web
    name: dungjit-ai
    env: python
    buildCommand: ""
    startCommand: gunicorn app:application
    envVars:
      - key: LINE_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: SHEET_NAME_USERS
        sync: false
      - key: SHEET_NAME_LOGS
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: 1234
      - key: LIFF_ID
        sync: false
      - key: GOOGLE_TYPE
        sync: false
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: GOOGLE_PRIVATE_KEY_ID
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_AUTH_URI
        sync: false
      - key: GOOGLE_TOKEN_URI
        sync: false
      - key: GOOGLE_AUTH_PROVIDER_X509_CERT_URL
        sync: false
      - key: GOOGLE_CLIENT_X509_CERT_URL
        sync: false

