services:
  - type: web
    name: duangjit-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: LINE_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LIFF_ID
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: 1234

